version: '3'
services:
   smtp-proxytunnel:
      build: .
      environment:
              - PROXY_SERVER=cooperate.proxyserver
              - PROXY_PORT=3128
              - TARGET_SERVER=smtp.yourmailhost.com 
              - TARGET_PORT=587
              - LOCAL_PORT=2222
      ports: 
              - "555:2222"
